name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Unit Tests with Pytest
      run: |
        pytest > test_report.txt
        cat test_report.txt

    - name: Run GitLeaks (Secret Scanning)
      uses: gitleaks/gitleaks-action@v2
  
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        sudo mv bin/trivy /usr/local/bin/


    - name: Build Docker Image
      run: docker build -t devsecops-app .

    - name: Run Trivy Scan on Docker Image
      run: trivy image --severity HIGH,CRITICAL devsecops-app > trivy_report.txt
  